@TodoApi_HostAddress = http://localhost:5062

POST {{TodoApi_HostAddress}}/api/todos
Content-Type: application/json

{
    "name": "walk dog",
    "isComplete": true
}

###

POST {{TodoApi_HostAddress}}/api/todos
Content-Type: application/json

{
  "name": "walk cat",
  "isComplete": false
}

###

GET {{TodoApi_HostAddress}}/api/todos

###

GET {{TodoApi_HostAddress}}/api/todos/1

###

PUT {{TodoApi_HostAddress}}/api/todos/1
Content-Type: application/json

{
  "id": 1,
  "name": "feed fish",
  "isComplete": false,
  "secret": "a secret"
}

###

DELETE {{TodoApi_HostAddress}}/api/todos/1

###

GET {{TodoApi_HostAddress}}/api/todos/complete