/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: v1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { todoInstance } from '../../config/http';
export interface TodoFeaturesTodosCommandsCreateTodoCommand {
  name?: string;
  isComplete?: boolean;
}

export interface TodoFeaturesTodosCommandsDeleteTodoCommand {
  id?: number;
}

export interface TodoFeaturesTodosCommandsToggleTodoCompleteCommand {
  id?: number;
}

export interface TodoFeaturesTodosCommandsUpdateTodoCommand {
  id?: number;
  name?: string;
  isComplete?: boolean;
}

export interface TodoFeaturesTodosModelsTodoItem {
  id?: number;
  /** @nullable */
  name?: string | null;
  isComplete?: boolean;
}

export type GetApiTodosParams = {
isComplete?: boolean;
};

export type PutApiTodosUpdateParams = {
id: number;
};

export type PutApiTodosToggleParams = {
id: number;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const postApiTodos = (
    todoFeaturesTodosCommandsCreateTodoCommand: TodoFeaturesTodosCommandsCreateTodoCommand,
 options?: SecondParameter<typeof todoInstance>,signal?: AbortSignal
) => {
      
      
      return todoInstance<TodoFeaturesTodosModelsTodoItem>(
      {url: `/api/todos`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: todoFeaturesTodosCommandsCreateTodoCommand, signal
    },
      options);
    }
  


export const getPostApiTodosMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiTodos>>, TError,{data: TodoFeaturesTodosCommandsCreateTodoCommand}, TContext>, request?: SecondParameter<typeof todoInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiTodos>>, TError,{data: TodoFeaturesTodosCommandsCreateTodoCommand}, TContext> => {

const mutationKey = ['postApiTodos'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiTodos>>, {data: TodoFeaturesTodosCommandsCreateTodoCommand}> = (props) => {
          const {data} = props ?? {};

          return  postApiTodos(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiTodosMutationResult = NonNullable<Awaited<ReturnType<typeof postApiTodos>>>
    export type PostApiTodosMutationBody = TodoFeaturesTodosCommandsCreateTodoCommand
    export type PostApiTodosMutationError = unknown

    export const usePostApiTodos = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiTodos>>, TError,{data: TodoFeaturesTodosCommandsCreateTodoCommand}, TContext>, request?: SecondParameter<typeof todoInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiTodos>>,
        TError,
        {data: TodoFeaturesTodosCommandsCreateTodoCommand},
        TContext
      > => {
      return useMutation(getPostApiTodosMutationOptions(options), queryClient);
    }
    
export const getApiTodos = (
    params?: GetApiTodosParams,
 options?: SecondParameter<typeof todoInstance>,signal?: AbortSignal
) => {
      
      
      return todoInstance<TodoFeaturesTodosModelsTodoItem[]>(
      {url: `/api/todos`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetApiTodosQueryKey = (params?: GetApiTodosParams,) => {
    return [
    `/api/todos`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetApiTodosQueryOptions = <TData = Awaited<ReturnType<typeof getApiTodos>>, TError = unknown>(params?: GetApiTodosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTodos>>, TError, TData>>, request?: SecondParameter<typeof todoInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiTodosQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiTodos>>> = ({ signal }) => getApiTodos(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiTodos>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiTodosQueryResult = NonNullable<Awaited<ReturnType<typeof getApiTodos>>>
export type GetApiTodosQueryError = unknown


export function useGetApiTodos<TData = Awaited<ReturnType<typeof getApiTodos>>, TError = unknown>(
 params: undefined |  GetApiTodosParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTodos>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTodos>>,
          TError,
          Awaited<ReturnType<typeof getApiTodos>>
        > , 'initialData'
      >, request?: SecondParameter<typeof todoInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTodos<TData = Awaited<ReturnType<typeof getApiTodos>>, TError = unknown>(
 params?: GetApiTodosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTodos>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTodos>>,
          TError,
          Awaited<ReturnType<typeof getApiTodos>>
        > , 'initialData'
      >, request?: SecondParameter<typeof todoInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTodos<TData = Awaited<ReturnType<typeof getApiTodos>>, TError = unknown>(
 params?: GetApiTodosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTodos>>, TError, TData>>, request?: SecondParameter<typeof todoInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiTodos<TData = Awaited<ReturnType<typeof getApiTodos>>, TError = unknown>(
 params?: GetApiTodosParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTodos>>, TError, TData>>, request?: SecondParameter<typeof todoInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiTodosQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





export const putApiTodosUpdate = (
    todoFeaturesTodosCommandsUpdateTodoCommand: TodoFeaturesTodosCommandsUpdateTodoCommand,
    params: PutApiTodosUpdateParams,
 options?: SecondParameter<typeof todoInstance>,signal?: AbortSignal
) => {
      
      
      return todoInstance<void>(
      {url: `/api/todos/update`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: todoFeaturesTodosCommandsUpdateTodoCommand,
        params, signal
    },
      options);
    }
  


export const getPutApiTodosUpdateMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiTodosUpdate>>, TError,{data: TodoFeaturesTodosCommandsUpdateTodoCommand;params: PutApiTodosUpdateParams}, TContext>, request?: SecondParameter<typeof todoInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiTodosUpdate>>, TError,{data: TodoFeaturesTodosCommandsUpdateTodoCommand;params: PutApiTodosUpdateParams}, TContext> => {

const mutationKey = ['putApiTodosUpdate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiTodosUpdate>>, {data: TodoFeaturesTodosCommandsUpdateTodoCommand;params: PutApiTodosUpdateParams}> = (props) => {
          const {data,params} = props ?? {};

          return  putApiTodosUpdate(data,params,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiTodosUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof putApiTodosUpdate>>>
    export type PutApiTodosUpdateMutationBody = TodoFeaturesTodosCommandsUpdateTodoCommand
    export type PutApiTodosUpdateMutationError = unknown

    export const usePutApiTodosUpdate = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiTodosUpdate>>, TError,{data: TodoFeaturesTodosCommandsUpdateTodoCommand;params: PutApiTodosUpdateParams}, TContext>, request?: SecondParameter<typeof todoInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiTodosUpdate>>,
        TError,
        {data: TodoFeaturesTodosCommandsUpdateTodoCommand;params: PutApiTodosUpdateParams},
        TContext
      > => {
      return useMutation(getPutApiTodosUpdateMutationOptions(options), queryClient);
    }
    
export const putApiTodosRemove = (
    todoFeaturesTodosCommandsDeleteTodoCommand: TodoFeaturesTodosCommandsDeleteTodoCommand,
 options?: SecondParameter<typeof todoInstance>,signal?: AbortSignal
) => {
      
      
      return todoInstance<void>(
      {url: `/api/todos/remove`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: todoFeaturesTodosCommandsDeleteTodoCommand, signal
    },
      options);
    }
  


export const getPutApiTodosRemoveMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiTodosRemove>>, TError,{data: TodoFeaturesTodosCommandsDeleteTodoCommand}, TContext>, request?: SecondParameter<typeof todoInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiTodosRemove>>, TError,{data: TodoFeaturesTodosCommandsDeleteTodoCommand}, TContext> => {

const mutationKey = ['putApiTodosRemove'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiTodosRemove>>, {data: TodoFeaturesTodosCommandsDeleteTodoCommand}> = (props) => {
          const {data} = props ?? {};

          return  putApiTodosRemove(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiTodosRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof putApiTodosRemove>>>
    export type PutApiTodosRemoveMutationBody = TodoFeaturesTodosCommandsDeleteTodoCommand
    export type PutApiTodosRemoveMutationError = unknown

    export const usePutApiTodosRemove = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiTodosRemove>>, TError,{data: TodoFeaturesTodosCommandsDeleteTodoCommand}, TContext>, request?: SecondParameter<typeof todoInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiTodosRemove>>,
        TError,
        {data: TodoFeaturesTodosCommandsDeleteTodoCommand},
        TContext
      > => {
      return useMutation(getPutApiTodosRemoveMutationOptions(options), queryClient);
    }
    
export const putApiTodosToggle = (
    todoFeaturesTodosCommandsToggleTodoCompleteCommand: TodoFeaturesTodosCommandsToggleTodoCompleteCommand,
    params: PutApiTodosToggleParams,
 options?: SecondParameter<typeof todoInstance>,signal?: AbortSignal
) => {
      
      
      return todoInstance<void>(
      {url: `/api/todos/toggle`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: todoFeaturesTodosCommandsToggleTodoCompleteCommand,
        params, signal
    },
      options);
    }
  


export const getPutApiTodosToggleMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiTodosToggle>>, TError,{data: TodoFeaturesTodosCommandsToggleTodoCompleteCommand;params: PutApiTodosToggleParams}, TContext>, request?: SecondParameter<typeof todoInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiTodosToggle>>, TError,{data: TodoFeaturesTodosCommandsToggleTodoCompleteCommand;params: PutApiTodosToggleParams}, TContext> => {

const mutationKey = ['putApiTodosToggle'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiTodosToggle>>, {data: TodoFeaturesTodosCommandsToggleTodoCompleteCommand;params: PutApiTodosToggleParams}> = (props) => {
          const {data,params} = props ?? {};

          return  putApiTodosToggle(data,params,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiTodosToggleMutationResult = NonNullable<Awaited<ReturnType<typeof putApiTodosToggle>>>
    export type PutApiTodosToggleMutationBody = TodoFeaturesTodosCommandsToggleTodoCompleteCommand
    export type PutApiTodosToggleMutationError = unknown

    export const usePutApiTodosToggle = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiTodosToggle>>, TError,{data: TodoFeaturesTodosCommandsToggleTodoCompleteCommand;params: PutApiTodosToggleParams}, TContext>, request?: SecondParameter<typeof todoInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiTodosToggle>>,
        TError,
        {data: TodoFeaturesTodosCommandsToggleTodoCompleteCommand;params: PutApiTodosToggleParams},
        TContext
      > => {
      return useMutation(getPutApiTodosToggleMutationOptions(options), queryClient);
    }
    
export const getApiTodosId = (
    id: number,
 options?: SecondParameter<typeof todoInstance>,signal?: AbortSignal
) => {
      
      
      return todoInstance<TodoFeaturesTodosModelsTodoItem>(
      {url: `/api/todos/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiTodosIdQueryKey = (id: number,) => {
    return [
    `/api/todos/${id}`
    ] as const;
    }

    
export const getGetApiTodosIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiTodosId>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTodosId>>, TError, TData>>, request?: SecondParameter<typeof todoInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiTodosIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiTodosId>>> = ({ signal }) => getApiTodosId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiTodosId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiTodosIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiTodosId>>>
export type GetApiTodosIdQueryError = unknown


export function useGetApiTodosId<TData = Awaited<ReturnType<typeof getApiTodosId>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTodosId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTodosId>>,
          TError,
          Awaited<ReturnType<typeof getApiTodosId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof todoInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTodosId<TData = Awaited<ReturnType<typeof getApiTodosId>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTodosId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTodosId>>,
          TError,
          Awaited<ReturnType<typeof getApiTodosId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof todoInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTodosId<TData = Awaited<ReturnType<typeof getApiTodosId>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTodosId>>, TError, TData>>, request?: SecondParameter<typeof todoInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiTodosId<TData = Awaited<ReturnType<typeof getApiTodosId>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTodosId>>, TError, TData>>, request?: SecondParameter<typeof todoInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiTodosIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
